GET https://chat-app-guts.herokuapp.com/api/people/person/e/e
###

GET https://chat-app-guts.herokuapp.com/chat/me

###

POST  https://chat-app-guts.herokuapp.com/chat
Content-Type: application/json

{
    "name": "me",
    "chatData": "1212"
}