GET https://chat-app-guts.herokuapp.com/chat

###

GET https://chat-app-guts.herokuapp.com/chat/me

###

POST  http://localhost:3000/chat
Content-Type: application/json

{
    "name": "me",
    "chatData": "1212"
}